# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  pkgs,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    # boot partition space is limited
    loader.grub.configurationLimit = 16;

    initrd = {
      availableKernelModules = [
        "xhci_pci"
        "thunderbolt"
        "nvme"
        "usbhid"
        "usb_storage"
        "sd_mod"
        "rtsx_pci_sdmmc"
      ];
      kernelModules = [ ];

      luks.devices."cryptroot" = {
        device = "/dev/disk/by-uuid/d21e14e9-2d33-441f-88bd-e303981248e3";
        crypttabExtraOpts = [
          "fido2-device=auto"
          "token-timeout=5s"
          "password-echo=no"
        ];
        allowDiscards = true;
      };

      # for luks fido2 device unlocking
      systemd = {
        enable = true;
        initrdBin = [ pkgs.kbd ];
        services.numlock = {
          description = "Enable NumLock in initrd TTYs";
          wantedBy = [ "cryptsetup.target" ];
          script = ''
            for tty in /dev/tty1; do
                /bin/setleds -D +num < "$tty";
            done
          '';
          serviceConfig.Type = "oneshot";
        };
      };
    };

    kernelModules = [ "kvm-intel" ];
    extraModulePackages = [ ];
  };

  fileSystems = {
    "/" = {
      device = "/dev/mapper/cryptroot";
      fsType = "btrfs";
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/8247-BFA8";
      fsType = "vfat";
      options = [
        "fmask=0077"
        "dmask=0077"
      ];
    };
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
