# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "virtio_pci" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/4d3c7f75-d1eb-46c0-842d-110f220a1a94";
      fsType = "btrfs";
      options = [ "subvol=root" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/4d3c7f75-d1eb-46c0-842d-110f220a1a94";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/de2dee16-4e23-417e-98bc-af179d5abcce"; }
    ];

}
