{
 "title": "Blocky Query Log",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "src", "query": "mysql" }
  ]
 },
 "panels": [
  {
   "title": "Most often (A)",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*) as c,\n  question_name\nFROM log_entries\nWHERE question_type = \"A\"\nGROUP BY question_name\nORDER BY c DESC"
    }
   ]
  },
  {
   "title": "Most often (AAAA)",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*) as c,\n  question_name\nFROM log_entries\nWHERE question_type = \"AAAA\"\nGROUP BY question_name\nORDER BY c DESC"
    }
   ]
  },
  {
   "title": "Most often blocked",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*) as c,\n  question_name\nFROM log_entries\nWHERE response_type = \"BLOCKED\" and question_type = \"A\"\nGROUP BY question_name\nORDER BY c DESC"
    }
   ]
  }
 ]
}