#!/bin/bash

# if XDG_DATA_HOME is not set, fail
if [ -z "$XDG_DATA_HOME" ]; then
    echo "XDG_DATA_HOME is not set"
    exit 1
fi

# get api key and fail if not set
API_KEY=$(cat "$XDG_DATA_HOME"/openai-key.txt)
if [ -z "$API_KEY" ]; then
    echo "API_KEY in $XDG_DATA_HOME/openai-key.txt is not set"
    exit 1
fi

question="$*"
model="gpt-3.5-turbo"

prompt=$(tr -d "\n" <<< "
Give me a bash command or script that best answers the following question
and list the used programs with package name in nixpkgs. If you
don't know the answers, guess and show confidence factor. Use
the following format:\n
[command]\n\n
Packages used:\n
- [package]\n\n
Confidence: [0-100]\n\n
QUESTION:\n
$question")

data=$(cat <<EOF
{
  "max_tokens": 256,
  "model": "$model",
  "messages": [{
    "role": "user",
    "content": "$prompt"
  }]
}
EOF
)

response=$(curl -s -X POST -H "Content-Type: application/json" \
  -H "Authorization: Bearer $API_KEY" \
  -d "$data" \
  https://api.openai.com/v1/chat/completions)

jq -r '.choices[0].message.content' <<< "$response" | sed -z 's/^\s*//'
