{
 "title": "Blocky Prometheus",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "src", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Blocking",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "blocky_blocking_enabled", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Domains blocked",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "blocky_blacklist_cache", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Resolve duration",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blocky_request_duration_ms_bucket{response_type=\"RESOLVED\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Downloads failed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "blocky_failed_download_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Time since last refresh",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(time() - blocky_last_list_group_refresh)/ sum(up{job=\"blocky\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache hit ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "blocky_cache_hit_count / (blocky_cache_hit_count + blocky_cache_miss_count)",
     "legendFormat": "Hit ratio"
    }
   ]
  },
  {
   "title": "Cache count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "targets": [
    { "expr": "blocky_cache_entry_count", "legendFormat": "Entries" }
   ]
  },
  {
   "title": "Requests / min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(client) (rate(blocky_query_total[5m])) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{job=\"blocky\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Query response types",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(response_type) (blocky_response_total)",
     "legendFormat": "{{response_type}}"
    }
   ]
  },
  {
   "title": "Query response reason",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "blocky_response_total", "legendFormat": "{{reason}}" }
   ]
  }
 ]
}